### PR TITLE
Add Caching spec

### PR DESCRIPTION
**Pull request by DevYukine**
first draft of caching spec, needs more discussion.

### CODE REVIEW

**Review by dondish — CHANGES_REQUESTED** [review]
Channels and roles shouldn't have the guild's id in their key.
Instead, I suggest saving the ids of the channels and roles in an array inside the guild's cache.
This will make sure the performance of listing roles and channels and looking up roles and channels without the guild's id will be O(1).

P.S
change "there" to "their" where needed.

**Comment by appellation** [comment]
I agree with @dondish that channels and roles shouldn't be dependent on guild IDs. I also think this should be done with emojis since they are global for bots.

Seeing as data stored using this proposed method would be serialized JSON, it will be challenging to update portions of it in cases where the entire updated object is not sent by Discord. I'm thinking of events like `CHANNEL_PINS_UPDATE` and `MESSAGE_UPDATE` (where the entire payload is not sent) or `GUILD_DELETE` on outages (where we may want to keep the guild data in cache but simply mark it as unavailable).

I'd be interested in getting a performance evaluation of this caching method since it requires some data manipulation on the frontend to process packets and then serialize their separate components into Redis. I'm particularly concerned about `GUILD_CREATE` events, which will spawn potentially thousands of Redis queries per guild to get all the roles, members, channels, and emojis into their respective maps.

As a smaller nit, this spec is basically only useful for Redis and should be described as such.

**Comment by appellation** [comment]
Members, roles, channels, and emoji IDs should not be stored in the serialized JSON of the guild as they will have to be atomically updated when they get added and removed. I recommend storing the IDs in a set.

**Comment by appellation** [comment]
>As a smaller nit, this spec is basically only useful for Redis and should be described as such.

@Drahcirius pointed out that a k/v cache spec is useful for more than just Redis, so maybe simply change the description from "in-memory" to "k/v".

**Comment by DevYukine** [comment]
Due to a discussing we decided that its the wrong way to do a spec, instead we will add a recommendation for caching.

**Pull request closed without merging**
